# =============================================
# Конфигурация Intel RealSense для антропоморфного робота
# Основная цель: получение RGB изображения и 3D координат объектов
# =============================================

# Основные настройки устройства
**camera_name: "camera"**
**serial_no: ""**                 # Если пусто, подключится к первой найденной камере
**usb_port_id: ""**               # Например: "2-1.4"
**device_type: ""**               # Например: "d435"
**reconnect_timeout: 10.0**       # Таймаут переподключения (сек)
**wait_for_device_timeout: 10.0** # Ожидание устройства (сек)
**initial_reset: false**          # Полный сброс устройства при запуске

# Настройка выходных данных и логирования
**log_level: "info"**             # Уровень детализации логов: 'debug', 'info', 'warn', 'error', 'fatal'
**output: "screen"**              # Куда выводить логи: 'screen' или 'log'

# Включение потоков данных (Streams)
**enable_color: true**            # ВКЛЮЧИТЬ: Цветная камера (RGB) - ОБЯЗАТЕЛЬНО
**enable_depth: true**            # ВКЛЮЧИТЬ: Камера глубины - ОБЯЗАТЕЛЬНО
**enable_infra: false**           # ВЫКЛЮЧИТЬ: Инфракрасный поток 0 (обычно не нужен)
**enable_infra1: false**          # ВЫКЛЮЧИТЬ: Инфракрасный поток 1
**enable_infra2: false**          # ВЫКЛЮЧИТЬ: Инфракрасный поток 2
**enable_gyro: true**            # ВЫКЛЮЧИТЬ: Гироскоп (для вашей задачи не нужен)
**enable_accel: true**           # ВЫКЛЮЧИТЬ: Акселерометр (для вашей задачи не нужен)
**enable_motion: true**           # Альтернативный режим для некоторых устройств

# Профили потоков (Разрешение и частота кадров)
# Формат: "ШиринаxВысотаxFPS" (например, "1280x720x30")
**rgb_camera.color_profile: "1280x720x30"**
**depth_module.depth_profile: "848x480x30"** # Хороший баланс между качеством и производительностью
**depth_module.infra_profile: "0,0,0"**      # Автовыбор, т.к. инфракрасные потоки выключены

# Форматы данных потоков
**rgb_camera.color_format: "RGB8"**
**depth_module.depth_format: "Z16"**
**depth_module.infra_format: "Y8"**
**depth_module.infra1_format: "Y8"**
**depth_module.infra2_format: "Y8"**

# Настройки автоэкспозиции
**rgb_camera.enable_auto_exposure: true**
**depth_module.enable_auto_exposure: true**

# Синхронизация потоков
**enable_sync: true**             # ВКЛЮЧИТЬ: Синхронизацию цветного и depth-изображения - ВАЖНО!
**depth_module.inter_cam_sync_mode: 0** # Режим синхронизации камер: 0-Выкл, 1-Ведущий, 2-Ведомый

# Настройки системы координат и трансформаций (TF)
**publish_tf: true**              # ВКЛЮЧИТЬ: публикацию трансформ - ОБЯЗАТЕЛЬНО
**tf_publish_rate: 30.0**         # Частота публикации динамических TF (Гц). Если камера подвижна.
**base_frame_id: "head_link"**    # Имя фрейма, на котором закреплена камера - ЗАМЕНИТЬ на свой!

# Фильтры постобработки глубины (УЛУЧШАЮТ КАЧЕСТВО ДАННЫХ)
# ВКЛЮЧИТЕ ИХ ПО ОДНОМУ ДЛЯ ТЕСТИРОВАНИЯ ЭФФЕКТА
**decimation_filter.enable: false**   # Уменьшение разрешения глубины для снижения шума
**spatial_filter.enable: true**       # УСТАНОВИТЬ true: Подавление пространственного шума
**temporal_filter.enable: true**      # УСТАНОВИТЬ true: Временное сглаживание (убирает мерцание)
**hole_filling_filter.enable: true**  # УСТАНОВИТЬ true: Заполнение "дыр" в данных глубины
**disparity_filter.enable: false**    # Включение преобразования disparity->depth (редко нужно)
**colorizer.enable: false**           # Визуализация глубины в RGB (только для отладки)

# Критически важные фильтры для вашей задачи
**align_depth.enable: true**       # ВКЛЮЧИТЬ: Выравнивание глубины по RGB - КРИТИЧЕСКИ ВАЖНО!
**pointcloud.enable: true**        # ВКЛЮЧИТЬ: Генерация облака точек - КРИТИЧЕСКИ ВАЖНО!

# Настройки облака точек
**pointcloud.stream_filter: 0**       # Какой поток использовать для текстуры: 0-Color, 1-Infra1, etc.
**pointcloud.stream_index_filter: 0** # Индекс потока
**pointcloud.ordered_pc: false**      # Сохранять порядок пикселей? (требует больше ресурсов)
**pointcloud.allow_no_texture_points: true** # Разрешить точки без текстуры

# Параметры обрезания дальности (ОЧЕНЬ ПОЛЕЗНО ДЛЯ РОБОТА)
**clip_distance: 2.5**              # Обрезать все точки дальше 2.5 метров - НАСТРОИТЬ ПОД ЗАДАЧУ!

# Настройки IMU (Инерциального блока) - ОТКЛЮЧЕНЫ, т.к. не нужны для статического позиционирования
**unite_imu_method: 2**             # 0 - не объединять (отдельные топики)  1 - copy: простое объединение 2 - linear_interpolation: ИНТЕРПОЛЯЦИЯ (РЕКОМЕНДУЕТСЯ)
**gyro_fps: 200**
**accel_fps: 200**
**linear_accel_cov: 0.01**
**angular_velocity_cov: 0.01**
**hold_back_imu_for_frames: false**

# Диагностика
**diagnostics_period: 1.0**         # Публиковать диагностику каждую секунду (0 - отключить)

# Дополнительные фильтры (экспериментальные)
**hdr_merge.enable: false**         # HDR режим для глубины (требует поддержки камеры)
**rotation_filter.enable: false**   # Поворот изображения (если камера перевернута)
**rotation_filter.rotation: 0.0**   # Угол поворота: 0.0, 90.0, 180.0, -90.0

# GPU ускорение (ВКЛЮЧАТЬ, ЕСЛИ СБОРКА БЫЛА С ПОДДЕРЖКОЙ GLSL)
**accelerate_gpu_with_glsl: false**